look for config and token

diff --git a/gptcmd b/gptcmd
--- a/gptcmd
+++ b/gptcmd
@@ -1,13 +1,27 @@
 #!/bin/bash
 
-source environment.sh
+CONF="/etc/gptcmd/gptcmd.conf"
+CREDS_FILE="$HOME/.gptcmd/credentials"
 
-TEMPERATURE=0.5
-MAX_TOKENS=100
-TOP_P=1.0
-FREQUENCY_PENALTY=0.2
-PRESENCE_PENALTY=0.0
-STOP="<EOF>"
+if [ -f "$CONF" ]; then
+  set -o allexport;
+  source "$CONF";
+  set +o allexport;
+else
+  echo "$CONF not found";
+  exit 1;
+fi;
+
+if [ -z "$GPT_TOKEN" ]; then
+  if [ -f "$CREDS_FILE" ]; then
+    set -o allexport;
+    source "$CREDS_FILE";
+    set +o allexport;
+  else
+    echo "$CREDS_FILE not found";
+    exit 1;
+  fi;
+fi;
 
 TRAIN=$(cat "$HOME/mks/gpt-cmd/train.txt" | sed -z "s/\n/$STOP/g;s/$STOP$/\n/")
 QUESTION="$TRAIN$STOP\0Q:$*$STOP"
@@ -21,7 +35,7 @@ BD=$(jq -n '{prompt: $prompt, temperature: $temp, max_tokens: $maxt, top_p: $top
   --argjson pres $PRESENCE_PENALTY \
   --arg stop "$STOP")
 
-RESP=$(curl -s https://api.openai.com/v1/engines/davinci/completions \
+RESP=$(curl -s "https://api.openai.com/v1/engines/$ENGINE/completions" \
   -H "Content-Type: application/json" \
   -H "Authorization: Bearer $GPT_TOKEN" \
   -d "$BD")
